#!/bin/bash

# @rhoads
# github.com/rhoadskj/dotfiles

if [ "$EUID" -ne 0 ]
    then echo "this script must be run as root!"
    exit
fi

sudo dnf -y install \
sddm \
mesa-dri-drivers \
polybar \
feh \
rofi \
kitty \
firefox \
vim \
git \
tree \
xclip \
alsa-lib \
alsa-utils \
pulseaudio \
pulseaudio-utils \
pavucontrol \
playerctl \
google-noto-* \
snapd

sudo dnf install \
libxcb-devel \
xcb-util-keysyms-devel \
xcb-util-devel \
xcb-util-wm-devel \
xcb-util-xrm-devel \
yajl-devel \
libXrandr-devel \
startup-notification-devel \
libev-devel \
xcb-util-cursor-devel \
libXinerama-devel \
libxkbcommon-devel \
libxkbcommon-x11-devel \
pcre-devel \
pango-devel \
git \
gcc \
automake

git clone https://www.github.com/Airblader/i3 i3-gaps && cd i3-gaps

utoreconf --force --install
rm -rf build/
mkdir -p build && cd build/
../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
make
sudo make install

cd .. && rm -rf i3-gaps

sudo systemctl set-default graphical.target
sudo systemctl reboot
