#!/bin/bash

# @rhoads
# github.com/rhoadskj/dotfiles

if [ "$EUID" -ne 0 ]
    then echo "this script must be run as root!"
    exit
fi

sudo dnf -y install \
i3 \
sddm \
mesa-dri-drivers \
polybar \
feh \
rofi \
kitty \
firefox \
vim \
git \
tree \
# thunar \ I'll come back to this
xclip \
alsa-lib \
alsa-utils \
pulseaudio \
pulseaudio-utils \
pavucontrol \
playerctl \
# light \ check to make sure this works on X
google-noto-* \
# grim \ might be wayland only?
# slurp \ might be wayland only?
snapd

sudo systemctl set-default graphical.target
sudo systemctl reboot
